name: schema_dart
description: Generate dart type definitions from PostgreSQL database schema.
homepage: https://github.com/osaxma
version: 0.0.1+4
repository: https://github.com/osaxma/schema-dart

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  args: ^2.3.0
  built_collection: ^5.1.1
  cli_util: ^0.3.5
  code_builder: ^4.1.0
  dart_style: ^2.2.1
  meta: ^1.7.0
  path: ^1.8.1
  postgres: ^2.4.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  schema-dart: schema_dart
